### ISSUE TITLE
Help kme I have a problem!

### ISSUE THREAD

**Issue by adambamba** [AMMA-2050/metrics_workshop#41]
I'm late for my train!

**Comment by cornkle** [comment]
Haha, stoopid! Btw, hope you spent your time at a nicer place than at the train station to wait for your train! In any case, if you were late, I'm sure Rory would have a nice, comfy sofa for you :p

**Comment by adambamba** [comment]
Rory is enjoying his graduation. 1 am is not a right to be waiting for a train at this periodOn 16 Dec 2016 23:35, cornkle <notifications@github.com> wrote:Haha, stoopid! Btw, hope you spent your time at a nicer place than at the train station to wait for your train! In any case, if you were late, I'm sure Rory would have a nice, comfy sofa for you :p

**Comment by claretandy** [comment]
Sorry Bamba, I think I wrote this when I was showing you how to raise an issue. I hope you managed to get back home safely. I'll send some photos around soon. 
Andy

**Comment by adambamba** [comment]
Hi dear all,
I'm having some issues when changing the monthly spi to the annual spi 
based on this script "spi_3m.py" in my fork.
Wish you Merry Christmas
