### ISSUE TITLE
Monthly spi to the annual spi

### ISSUE THREAD

**Issue by adambamba** [AMMA-2050/metrics_workshop#44]
Hi dear all,
I'm having some issues when changing the monthly spi to the annual spi
based on this script "spi_3m.py" in my fork. I have tried to aggregate per year but not  working.
Wish you all happy new year.

**Comment by cornkle** [comment]
Hi Bamba, 
I looked over the SPI code today and adapted it to work for any number of months (so possible to do with 1,3,6, 12 or whatever number of months). This means that only the 3-yearly version is still to do but has to be tackled in a different way than the current SPI code version. This structure is now compatible with the new metrics computation framework, which we'll be introducing very soon. I send you the code per mail to look through it.
