### ISSUE TITLE
commit fa262e7 

### ISSUE THREAD

**Issue by js08rgjf** [AMMA-2050/metrics_workshop#60]
Hey,

Think I have screwed up this one. I have managed to push plot_histogram_all_scenarios.py to my personal fork but do not seem to be able to make a pull request to put this on master. Where have I gone wrong?

Rory

**Comment by cornkle** [comment]
maybe check whether you have two branches in your fork. there should be a pull request button for the branch where you uploaded your changes to. Sometimes you don't get the big green pull request button for some reason. but there should still be a small one if there are changes to commit :)
